name: reclip
description: A new Flutter project.

version: 2.1.7+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  cloud_firestore: ^0.13.0+1
  flutter_spinkit: ^4.1.1+1
  flutter_custom_dialog: ^1.0.16
  image_picker: ^0.6.3+1
  flutter_screenutil: ^1.0.2
  firebase_storage: ^3.1.1
  flutter_advanced_networkimage: ^0.7.0
  shimmer: ^1.0.1
  curved_navigation_bar: ^0.3.2
  pull_to_refresh: ^1.5.8
  flushbar: ^1.9.1
  flutter_svg: ^0.17.3+1
  path_provider: ^1.6.5
  # flutter_ffmpeg: ^0.2.10
  # percent_indicator: ^2.1.1+1
  chewie: ^0.9.10
  flutter_ffmpeg: ^0.2.10

  #Authentication Packages
  firebase_auth: ^0.15.4
  firebase_core: ^0.4.3+2
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^3.0.0
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11+1
  uuid: ^2.0.4 #This is used for generating random content creator ids

  url_launcher: ^5.4.1
  flare_flutter: ^2.0.1
  flutter_launcher_icons: ^0.7.4

  sailor: ^0.6.0
  font_awesome_flutter: ^8.5.0

  equatable: ^1.0.3
  flutter_bloc: ^3.1.0

  auto_size_text: ^2.1.0
  flutter_form_builder: ^3.7.3
  flutter_picker: ^1.1.0

  cupertino_icons: ^0.1.2
  progress_dialog: ^1.2.0
  cached_network_image: ^2.0.0
  progressive_image: ^1.0.1
  expand_widget: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: "GothamHTF"
      fonts:
        - asset: assets/fonts/gotham/GothamHTF-Black.otf
          weight: 900
        - asset: assets/fonts/gotham/GothamHTF-Bold.otf
          weight: 700
        - asset: assets/fonts/gotham/GothamHTF-Book.otf
        - asset: assets/fonts/gotham/GothamHTF-Light.otf
          weight: 300
        - asset: assets/fonts/gotham/GothamHTF-Medium.otf
          weight: 500
        - asset: assets/fonts/gotham/GothamHTF-Thin.otf
          weight: 100
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
