name: reclip
description: A new Flutter project.

version: 2.3.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  dartz: ^0.9.0
  media_info: ^0.6.1

  freezed_annotation: ^0.7.1

  json_annotation: ^3.0.1

  image_picker: ^0.6.5+3
  flutter_screenutil: ^1.0.2
  flutter_advanced_networkimage: ^0.7.0
  shimmer: ^1.1.1
  curved_navigation_bar: ^0.3.2
  flushbar: ^1.10.0
  flutter_svg: ^0.17.3+1
  path_provider: ^1.6.5
  chewie: ^0.9.10
  firebase_messaging: ^6.0.12
  flutter_hooks: ^0.9.0
  connectivity: ^0.4.8+2
  device_preview: ^0.3.0+1
  simple_animations: ^1.3.11

  #Utilities

  #Authentication Packages
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  uuid: ^2.0.4 #This is used for generating random content creator ids

  #Firebase Dependencies
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.5
  admob_flutter: ^1.0.0-beta.2

  url_launcher: ^5.4.5
  flare_flutter: ^2.0.3
  flutter_launcher_icons: ^0.7.4

  font_awesome_flutter: ^8.5.0
  auto_route: ^0.4.5
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0

  auto_size_text: ^2.1.0
  flutter_form_builder: ^3.8.3
  flutter_picker: ^1.1.0

  cupertino_icons: ^0.1.2
  expand_widget: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.4.8
  build_runner: ^1.8.0
  json_serializable: ^3.3.0
  freezed: ^0.10.7
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: "GothamHTF"
      fonts:
        - asset: assets/fonts/gotham/GothamHTF-Black.otf
          weight: 900
        - asset: assets/fonts/gotham/GothamHTF-Bold.otf
          weight: 700
        - asset: assets/fonts/gotham/GothamHTF-Book.otf
        - asset: assets/fonts/gotham/GothamHTF-Light.otf
          weight: 300
        - asset: assets/fonts/gotham/GothamHTF-Medium.otf
          weight: 500
        - asset: assets/fonts/gotham/GothamHTF-Thin.otf
          weight: 100
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
